### ISSUE TITLE
Add taxi command

### ISSUE THREAD

**Issue by gcruicks** [PilotsTradeNetwork/BoozeBot#292]
Source destination departure 
Post to announcements?

**Comment by SirDoofusMcDingbat** [comment]
-command should be /departure
-should use a dropdown box with options for N0, N1, N2, Gali, and maybe Mandhrithar
-command should include a hitchhiker ping if and only if trip is from N2 -> N1 or N1->N0
-possibly allow a departure from N2 -> N0 with ping but ideally they would be posting N2->N1 and then a second one into N0
-needs option to add hammertime timestamp, or maybe UTC time and have it convert that into timestamp?
-Should post precise times for departures from gali but just post :thoon: for departures from N2 and above
-possibly add an option to depart to/from custom systems, but not critical
-would post in departures channel
-possibly a way for the user to remove the departure?
