### ISSUE TITLE
Add wine_tanker and wine_carrier flags

### ISSUE THREAD

**Issue by Randomgazz** [PilotsTradeNetwork/BoozeBot#309]
Add support for wine_tanker and wine_carrier flags based on user form input

**Comment by gcruicks** [comment]
On top of this, likely need to track how often the carrier was a tanker/carrier for the cruise to handle multiple trips. That impacts the duplication checks.

- also consider changing embed to show carrier count/wine total vs tankers.
- find with wine logic needs redesigned to handle finding a carrier or a tanker
- Any calculation needs to validate both carrier/tanker status 
- 

Do we need a second table or just reuse the current one?
